### ISSUE TITLE
Autofill of arrow functions in component event is wrong

### ISSUE THREAD

**Issue by j-delaney** [sveltejs/svelte-repl#148] opened 2021-01-21 23:58 UTC
When using an arrow function in a component event, typing `>` makes the REPL think you're completing the HTML tag and it will autofill inccorectly.

# Example
![SvelteReplRepro](https://user-images.githubusercontent.com/3589480/105426892-ea653e80-5c43-11eb-8637-d0af1dab4d4b.gif)

# Steps to reproduce

In the REPL if you have the following:
```
<button on:click={() =}
```
and the cursor is between `=` and `}` and then you type `>` it will autofill with the following:
```
<button on:click={() =>
	
</button>}
```

When no autofill is expected. It should look like:
```
<button on:click={() =>}
```

**Comment by j-delaney** [comment] 2021-01-22 00:01
Looks like an issue with the `closetags` plugin to CodeMirror. You can reproduce this bug on https://codemirror.net/demo/closetag.html

**Comment by Conduitry** [comment] 2021-01-22 00:11
Yeah. This is a duplicate of #24. I'm not really sure there's an easy way to handle this without writing our whole own plugin.

**Closed by Conduitry** 2021-01-22 00:11 UTC
