### ISSUE TITLE
Removing a saved REPL from https://svelte.dev/apps

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/svelte-repl#153] opened 2021-03-11 15:44 UTC
Specifically: I have a few random duplicates (forks) that do not differ in anything, but they cannot be deleted from https://svelte.dev/apps.
Will there be an option to remove a saved REPL?

**Comment by Conduitry** [comment] 2021-03-11 15:53
Probably eventually. Duplicate of https://github.com/sveltejs/svelte/issues/3457

**Closed by Conduitry** 2021-03-11 15:53 UTC

**Comment by lukaszpolowczyk** [comment] 2021-03-11 15:58
@Conduitry It's a different repo. : /
Move issue to svelte-repl there, because I only looked in svelte-repl before adding the post.

**Comment by antony** [comment] 2021-03-11 16:18
@lukaszpolowczyk the repl project doesn't deal with persisting, that is handled by the svelte site which lives inside the `svelte` repo, hence why the issue belongs there.
