### ISSUE TITLE
Breaks when javascript content contains `</script>`

### ISSUE THREAD

**Issue by ggoodman** [sveltejs/svelte-repl#126] opened 2020-07-14 19:42 UTC
❤️  [Reproduction](https://svelte.dev/repl/2198dd61f4ab452db9af44e1a315b9da?version=3.24.0)

**Comment by Conduitry** [comment] 2020-07-14 20:00
This is a duplicate of https://github.com/sveltejs/svelte/issues/3039 / https://github.com/sveltejs/svelte/issues/3840 / https://github.com/sveltejs/svelte/issues/4406 / https://github.com/sveltejs/svelte/issues/4996 / https://github.com/sveltejs/svelte/issues/5024 / maybe others, and is not a bug. This is how parsing inline script tags works in HTML.

**Closed by Conduitry** 2020-07-14 20:00 UTC

**Comment by ggoodman** [comment] 2020-07-15 00:30
Good news is that now we have a tombstone in this repo too 😂.

I did do a search but not in the right repo.
