### ISSUE TITLE
false positive infinite loop detected with async generator

### ISSUE THREAD

**Issue by m59peacemaker** [sveltejs/svelte-repl#109] opened 2020-04-30 22:35 UTC
https://svelte.dev/repl/c42e039670d14b3a807aa6576dd3c86b?version=3.21.0

It seems like something about `for await` iterating an async generator that has a `while` or `for` loop in it triggers the infinite loop detection. Granted, it *is* an infinite loop, just not in the same sense this detection is meant to block.

**Comment by Conduitry** [comment] 2020-04-30 22:51
Probably a duplicate of https://github.com/sveltejs/svelte/issues/4698 which has a fix https://github.com/sveltejs/svelte/pull/4716 to be released in the next Svelte version.

**Comment by Conduitry** [comment] 2020-05-05 02:05
Indeed a duplicate of 4698, and fixed in 3.22.0 https://svelte.dev/repl/c42e039670d14b3a807aa6576dd3c86b?version=3.22.0

**Closed by Conduitry** 2020-05-05 02:05 UTC
